### PR TITLE
change goal format to block-gripper-informed goal

### PR DESCRIPTION
**Pull request by dion-jy**
## Description
Peek 2021-10-20 00-01

### Feature
1. changed goal format to block-gripper-informed.
  - final_goal -> block-informed
  - sub_goal -> block-gripper-informed
  - (that's why codes are messed up now. need to clean the codes later.)
2. visualize subgoals
  - obvious boxes(red one and green one) -> now states of objects
  - ghost boxes(red one and green one) -> targets of objects
  - ghost spheres
    - red one and green one -> subgoals of objects
    - black one -> subgoals of ee position

## Checklist

- [x] this code is auto-formatted using `make format`
- [x] I updated the READMEs and the documentation, if necessary.

### CODE REVIEW

**Review by benthebear93 — COMMENTED** [review]
Just little opinion on initializing lists

**Comment by CUN-bjy** [comment]
@benthebear93 Could you make an experiment for now version of models? I don't have enough time to develop these days because of my personal mission. I'll develop more after achieving those! And please merge it after experiments.

**Comment by benthebear93** [comment]
@CUN-bjy  i will do it today!

**Comment by benthebear93** [comment]
somethings_not_right
Screenshot from 2021-11-03 12-47-05
Screenshot from 2021-11-03 12-48-15


@CUN-bjy Something is definitely wrong. but i will merge it now.

**Review by benthebear93 — APPROVED** [review]

**Comment by dion-jy** [comment]
T.T

**Comment by dion-jy** [comment]
note-keeping(this is why we have to use normalized inputs. but actually the results are not just driven because of this.)
https://nhigham.com/2020/08/04/what-is-numerical-stability/

**Pull request merged**
